### ISSUE TITLE
Support dynamic labels from cached topic messages

### ISSUE THREAD

**Issue by AnthonyCvn** [reductstore/website#198]
Allow pipelines to attach dynamic labels to each stored record using the latest message from a specified ROS 2 topic. The topic is treated as a "latched" source (its latest message is cached and fields are extracted at write time based on a configuration mapping).

Example use case: extract `mission_id` and `operator` fields from `/mission_info` to label all records during the mission.

Configuration format:

```yaml
labels:
  dynamic:
    topic: /mission_info
    fields:
      mission_id: mission_id
      operator: operator
```

This should be implemented per pipeline.
